### ISSUE TITLE
Datenbank erstellen

### ISSUE THREAD

**Issue by Midoti** [TobiasM2000/TelegramHochwasseralarm#14]

**Comment by matze0riz0r** [comment]
I added @matze0riz0r and @h4ckt1c to discuss docker integration

**Comment by h4ckt1c** [comment]
Infuxdb wurde ja schon vorgeschlagen, falls ja:

- Version 1.8 oder 2.0?
- Als Docker Container?

NodeRed läuft auch bereits als Docker Container.
