### ISSUE TITLE
TTN Node-RED Package installieren

### ISSUE THREAD

**Issue by Lurons** [TobiasM2000/TelegramHochwasseralarm#7]

**Comment by h4ckt1c** [comment]
Vorschlag: NodeRed als Docker Container installieren?!

**Comment by Lurons** [comment]
> Vorschlag: NodeRed als Docker Container installieren?!

Ich habe mit Docker Container noch nicht gearbeitet. Das hört sich, aber
zudem was ich bis jetzt gelesen habe, sehr solide an. Ich finde das gut 👍.  Ist nur die Frage, ob ihr das erstmal noch mit den anderen besprechen wollt.

**Comment by h4ckt1c** [comment]
Wenn wir uns gemeinsam darauf einigen, würde ich mir den "Schuh" gerne anziehen. Ich habe schon viel damit gearbeitet und es hat echt wahnsinnige Vorteile.

- Im Falle eines Systemausfalls kann eine neue Instanz mit sehr geringem Aufwand hochgezogen werden
- Es muss nichts installiert werden (außer Docker)
- Man kann lokal (via Docker) testen/planen/einrichten und wenn alles läuft kann dieser Container überall gestartet werden
- Über Volumes können Daten auf einfache Art gesichert und übertragen werden.
- und und und 😂

**Comment by Lurons** [comment]
Ja hört sich sehr gut an und bin auch dafür. Ich habe es jetzt nochmal an unsere Hardware-Leute weitergeben, damit sie auch mal ihren Senf dazu beitragen können. Ansonsten würde ich sagen, dass wir das so umsetzten 😉.

**Comment by h4ckt1c** [comment]
NodeRed wurde als Docker Container installiert. Issue kann geschlossen werden.
